kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lambda-cluster-access
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/eviction", "nodes"]
    verbs: ["create", "list", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lambda-user-cluster-role-binding
subjects:
  - kind: User
    name: lambda
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: lambda-cluster-access
  apiGroup: rbac.authorization.k8s.io
